import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
//import ListItems from 'components/listHour'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const horarios = [{hora:'09:30', checkIn: false},
                    {hora:'10:00', checkIn: false},
                    {hora:'10:30', checkIn: false},
                    {hora:'11:00', checkIn: false},
                    {hora:'11:30', checkIn: false},
                    {hora:'12:00', checkIn: false},
                    {hora:'12:30', checkIn: false},
                    {hora:'13:00', checkIn: false},
                    {hora:'13:30', checkIn: false},
                    {hora:'14:00', checkIn: false},
                    {hora:'14:30', checkIn: false},
                    {hora:'15:00', checkIn: false},
                    {hora:'15:30', checkIn: false},
                    {hora:'16:00', checkIn: false},
                    {hora:'16:30', checkIn: false},
                    {hora:'17:00', checkIn: false},
                    {hora:'17:30', checkIn: false},
                    {hora:'18:00', checkIn: false},
                    {hora:'18:30', checkIn: false},
                    {hora:'19:00', checkIn: false},
                    {hora:'19:30', checkIn: false},
                    {hora:'20:00', checkIn: false},
                    {hora:'20:30', checkIn: false},
                    {hora:'21:00', checkIn: false},
                    {hora:'21:30', checkIn: false}]
  const [horasState, setHorarioState] = useState(horarios)
  const listItems = () => {
 
    const listItems = horasState.map( (horario, index) =>
  
      <h2 
        id={'hora_'+index}
        key={index} 
        className={styles.horario}
        onClick={(number)=> handleClickHorario(number)} 
      >
        {horario.hora}
      </h2>
  
    );
    return (
      <div className={styles.hourContainer}>{listItems}</div>
    );
  }
  
    //Marca el horario nuevo
  const handleClickHorario = ({target}) => {

      let id = target.id.replace('hora_', '')

      if(!horasState[id].checkIn){

        target.className = styles.horarioBlock;
        horasState[id].checkIn = true
      }else{

        target.className = styles.horario;
        horasState[id].checkIn = false
      }

  }


  return (
    <> 
      <Head>
        <title>Pedido de vehiculos por horarios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1 className={styles.description}>
        Pedido de vehiculos por horarios
      </h1>
      {listItems()}
      </main>
    </>
  )
}
